language: node_js
sudo: false
script: gulp
node_js:
  - "5"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  - CXX=g++-4.8
